config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', controllers: { registrations: "user_registrations" } }
  root 'simple_pages#index'
  resources :products do
  resources :comments
end
resources :users
  get 'simple_pages/product'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'
  get 'simple_pages/landing_page'

  post 'payments/create'
  get 'payments/create'
  
  post 'simple_pages/thank_you'
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'orders/create'
  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where('user_id = ?', current_user.id)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id 

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_url, notice: 'Order was successfully created.' }
        format.json { render :index, status: :created, location: @order }
      else
        format.html { redirect_to orders_url, notice: 'Order was not successfully created.' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  end


  def update

  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:product_id, :total)
    end
  end

app/views/orders/index.html.erb
<div class="container" id="container-order">
	<h2>orders</h2>
	<p>The .table-striped class adds zebra-stripes to a table:</p>
	<table class="table table-striped">
		<thead>
			<tr>

				<th>product</th>
				<th>total</th>
			</tr>
		</thead>
		<%@orders.each do |order| %>
		<tr>
			<td><%=order.product_id%></td>
			<td><%=order.total%></td>
			<td><div class="btn btn-info btn-xs"><%=link_to 'Show', order %></div></td>
        <td><div class="btn btn-info btn-xs"><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></div></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/orders/show.html.erb
<div class="container" id="container-order">

<h2>orders</h2>
  <p>The info of order</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>product id</th>
        <th>total</th>

      </tr>
    </thead>
      <tr>
        <td><%= @order.product_id %></td>
        <td><%= @order.total %></td>
        <td><div class="btn btn-info btn-xs"><%= link_to 'Back', orders_path %></div></td>
      </tr>
  </table>
</div>